# For local development only.
channels:
  - "pytorch"
  - "conda-forge"
dependencies:
  - pytorch==2.0.1
  # HuggingFace
  - datasets==2.12.0
  - tokenizers==0.13.3
  - transformers==4.29.1
  # Loading Datasets
  - pandas==2.0.1
  - pyarrow==10.0.1
  # Tracking
  - neptune==1.0.2
  # Utilities
  - tqdm==4.65.0
  - boto3==1.26.131
