channels:
  - "pytorch-nightly"
  - "conda-forge"
dependencies:
  - python==3.10
  - pytorch
  # HuggingFace
  - datasets==2.12.0
  - tokenizers==0.13.3
  # Loading Datasets
  - pandas==2.0.0
  - pyarrow==10.0.1
  # Tracking
  - neptune==1.0.2
  # Utilities
  - tqdm==4.65.0
