name: Build Docker Image
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker build --rm=false -t ghcr.io/rojas-diego/gopilot:latest -t docker.io/rojasdiego/gopilot:latest .
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push to GitHub Package Registry
        run: docker push ghcr.io/rojas-diego/gopilot:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: rojasdiego
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push docker.io/rojasdiego/gopilot:latest
